import React,{useEffect,useRef,useState} from "react";
import { toast } from "sonner";
import Model3DViewer from "./viewers/Model3DViewer";
import type { Prompt3DFinishJobStatus } from "../../shared/prompt3dWorkflow";
import type { DeformationRegion } from "../../shared/deformationRegions";
import { REGION_COLORS,resolveRegionInstruction,type RegionDefinition,type RegionColor } from "../../shared/deformationRegionModel";

const input="w-full rounded border border-line bg-bg p-2 text-sm";
export default function DeformationRegionEditor({job,onClose,onSaved}:{job:Prompt3DFinishJobStatus;onClose:()=>void;onSaved:(job:Prompt3DFinishJobStatus)=>void}){
  const [regions,setRegions]=useState<DeformationRegion[]>([]),[definitions,setDefinitions]=useState<RegionDefinition[]>([]);
  const [initial,setInitial]=useState<RegionDefinition[]>([]),[undo,setUndo]=useState<RegionDefinition[][]>([]);
  const [selected,setSelected]=useState<string|null>(null),[instruction,setInstruction]=useState("");
  const [preview,setPreview]=useState<{path:string;regions:DeformationRegion[];clipName?:string}|null>(null),[error,setError]=useState("");
  const [working,setWorking]=useState(false),[saving,setSaving]=useState(false),[showInfluence,setShowInfluence]=useState(true);
  const [readyPath,setReadyPath]=useState("");const serial=useRef(0);
  const changed=JSON.stringify(initial)!==JSON.stringify(definitions);
  const selectedRegion=definitions.find(r=>r.id===selected);
  useEffect(()=>{let live=true;void window.grudge.prompt3d.inspectDeformation(job.id).then((result:any)=>{if(!live)return;setRegions(result.regions);setDefinitions(result.definitions);setInitial(result.definitions);setSelected(result.definitions[0]?.id??null);setPreview({path:job.assetPath!,regions:result.regions,clipName:result.clipName});}).catch((e:unknown)=>live&&setError(String(e)));return()=>{live=false;serial.current++;};},[job.id]);
  useEffect(()=>{
    if(!definitions.length)return;
    const sequence=++serial.current;setWorking(true);setError("");
    const timer=setTimeout(()=>{void window.grudge.prompt3d.previewDeformation({jobId:job.id,sha256:job.sha256!,regions:definitions}).then((result:any)=>{if(sequence!==serial.current)return;setPreview(result);setReadyPath("");}).catch((e:unknown)=>{if(sequence===serial.current)setError(String(e));}).finally(()=>{if(sequence===serial.current)setWorking(false);});},350);
    return()=>clearTimeout(timer);
  },[definitions,job.id]);
  useEffect(()=>{if(!definitions.some(r=>r.id===selected))setSelected(definitions[0]?.id??null);},[definitions,selected]);
  function commit(next:RegionDefinition[]){setUndo(old=>[...old.slice(-19),definitions]);setDefinitions(next);}
  function patch(update:Partial<RegionDefinition>){if(!selected)return;commit(definitions.map(r=>r.id===selected?{...r,...update}:r));}
  function apply(){try{const result=resolveRegionInstruction(instruction,definitions,selected);setSelected(result.region.id);commit(definitions.map(r=>r.id===result.region.id?result.region:r));setInstruction("");toast.success(result.message);}catch(e){setError(String(e));}}
  function add(){const id=`custom-${crypto.randomUUID()}`;const color=Object.keys(REGION_COLORS).find(c=>!definitions.some(r=>r.color===c)) as RegionColor??"red";const r:RegionDefinition={id,name:`Custom area ${definitions.filter(r=>r.kind==="custom").length+1}`,color,kind:"custom",center:[.5,.5,.5],extent:[.8,.8,.8],operation:"move",axis:"y",amount:.05,strength:1};commit([...definitions,r]);setSelected(id);}
  async function save(){if(working||saving||error||!changed||preview?.path!==readyPath)return;setSaving(true);try{const result=await window.grudge.prompt3d.finishStart({source:job.source,operation:"animation",instruction:`Adjust named moving areas of retained animation ${job.id}`,seed:job.seed,animation:{provider:"auto-cpu",mode:"replace",deformationEdit:{jobId:job.id,sha256:job.sha256!,regions:definitions}}});onSaved(result);}catch(e){setError(String(e));}finally{setSaving(false);}}
  const targets=preview?.regions.find(r=>r.id===selected)?.targetNames??regions.find(r=>r.id===selected)?.targetNames??[];
  return <section className="space-y-3 rounded border border-sky-500/40 bg-bg-2 p-3" aria-label="Deformation region editor">
    <div className="flex items-center justify-between"><div><b>Adjust moving areas</b><p className="text-xs text-muted">Working preview · the original model and its approval remain unchanged.</p></div><button className="rounded border border-line px-3 py-1 text-xs" onClick={onClose}>Close</button></div>
    <label className="block text-xs">Describe one adjustment<textarea aria-label="Region instruction" className={input+" mt-1 min-h-16"} value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder='Make the red region weaker, or bend tail tip sideways 20 degrees.'/></label>
    <div className="flex flex-wrap gap-2"><button className="rounded bg-gold px-4 py-2 text-sm font-semibold text-black disabled:opacity-35" disabled={!instruction.trim()||saving} onClick={apply}>Preview adjustment</button><button className="rounded border border-line px-3 py-1 text-xs disabled:opacity-35" disabled={!undo.length||saving} onClick={()=>{const previous=undo.at(-1)!;setDefinitions(previous);setUndo(undo.slice(0,-1));}}>Undo</button><button className="rounded border border-line px-3 py-1 text-xs disabled:opacity-35" disabled={!changed||saving} onClick={()=>commit(initial)}>Reset all</button></div>
    <div className="flex flex-wrap items-center gap-2"><label className="flex-1 text-xs">Moving area<select aria-label="Moving area" className={input+" mt-1"} value={selected??""} onChange={e=>setSelected(e.target.value)}>{definitions.map(r=><option key={r.id} value={r.id}>{r.name} · {r.color} · {Math.round(r.strength*100)}%</option>)}</select></label><button className="rounded border border-line px-3 py-2 text-xs disabled:opacity-35" disabled={definitions.filter(r=>r.kind==="custom").length>=4||saving} onClick={add}>Add area</button><label className="text-xs"><input type="checkbox" checked={showInfluence} onChange={e=>setShowInfluence(e.target.checked)}/> Show influence</label></div>
    {selectedRegion&&<details className="rounded border border-line p-2" open={selectedRegion.kind==="custom"}><summary className="cursor-pointer text-xs">Name, colour and {selectedRegion.kind==="custom"?"coverage":"motion settings"}</summary><div className="mt-2 grid gap-2 md:grid-cols-2"><label className="text-xs">Name<input aria-label="Region name" className={input} maxLength={48} value={selectedRegion.name} onChange={e=>patch({name:e.target.value})}/></label><label className="text-xs">Colour<select aria-label="Region colour" className={input} value={selectedRegion.color} onChange={e=>patch({color:e.target.value as RegionColor})}>{Object.keys(REGION_COLORS).map(c=><option key={c}>{c}</option>)}</select></label></div>
      {selectedRegion.kind==="custom"&&<div className="mt-2 grid gap-2 md:grid-cols-3">{["Sideways · X","Up/down · Y","Forward/back · Z"].map((label,i)=><div key={label}><label className="block text-xs">{label} placement <input aria-label={`${label} placement`} type="range" min="0" max="1" step=".01" value={selectedRegion.center[i]} className="w-full" onChange={e=>{const center=[...selectedRegion.center] as RegionDefinition["center"];center[i]=Number(e.target.value);patch({center});}}/></label><label className="block text-xs">Coverage <input aria-label={`${label} coverage`} type="range" min=".02" max="2" step=".01" value={selectedRegion.extent[i]} className="w-full" onChange={e=>{const extent=[...selectedRegion.extent] as RegionDefinition["extent"];extent[i]=Number(e.target.value);patch({extent});}}/></label></div>)}</div>}
      <p className="mt-2 text-[11px] text-muted">{selectedRegion.kind==="custom"?"Custom ellipsoid with a smooth falloff to zero at its edge.":"This area comes from the retained animation's actual morph deltas; its label does not certify anatomy."} Instructions use model directions. Use degrees for bend/swing/rotate, and percentages for move/scale.</p>
    </details>}
    <div role="status" className={error?"text-xs text-red-300":"text-xs text-muted"}>{error|| (working?"Updating the exact local preview…":changed?"Preview ready. Review the motion, then save a new revision.":"Select an area or name it in your instruction.")}</div>
    {preview&&<div className="relative h-[520px] overflow-hidden rounded border border-line">{showInfluence&&selectedRegion&&<div className="pointer-events-none absolute left-3 top-3 z-10 rounded bg-black/80 px-3 py-1 text-sm" style={{color:REGION_COLORS[selectedRegion.color]}}>{selectedRegion.name} · {selectedRegion.color}</div>}<Model3DViewer asset={{name:"region-preview.glb",url:`local://${encodeURIComponent(preview.path)}`,localPath:preview.path,contentType:"model/gltf-binary",size:0}} preserveAuthoredMaterials preferredClipName={preview.clipName} highlightRegion={showInfluence&&selectedRegion?{targetNames:targets,color:REGION_COLORS[selectedRegion.color],label:selectedRegion.name}:undefined} onLoadStateChange={s=>{setReadyPath(s.status==="ready"?s.assetPath:"");if(s.status==="error")setError(s.error??"Preview failed to load.");}}/></div>}
    <p className="text-[11px] text-muted">Highlight = relative movement within the selected area. Dark vertices are unaffected by that area. X sideways · Y up/down · Z forward/back; camera orbit does not change these directions. Areas can overlap.</p>
    <button className="rounded bg-gold px-4 py-2 text-sm font-semibold text-black disabled:opacity-35" disabled={!changed||working||saving||Boolean(error)||!preview||readyPath!==preview.path} onClick={()=>void save()}>Save adjusted animation</button>
  </section>;
}
