/** Grudge Studio fleet game catalog — Steam-style launcher entries. */

export type GameCategory = "action" | "rpg" | "rts" | "racing" | "puzzle" | "demo" | "tool" | "mobile";
export type GameStatus = "live" | "active" | "beta" | "planned";

export interface FleetGame {
  id: string;
  name: string;
  displayName: string;
  description: string;
  url: string;
  repo: string;
  engine: string;
  status: GameStatus;
  category: GameCategory;
  topics: string[];
  thumbnail?: string;
  hasServer?: boolean;
  /** Optional GitHub release download page */
  releasesUrl?: string;
}

const THUMB = (repo: string) =>
  `https://opengraph.githubassets.com/1/MolochDaGod/${repo}`;

/** Static fleet catalog — merged with live grudgedot /api/games when available. */
export const FLEET_GAMES: FleetGame[] = [
  {
    id: "open-launcher",
    name: "gameopen",
    displayName: "Open Launcher",
    description: "Steam-style fleet library + combat labs + SSO hub (canonical play entry).",
    url: "https://open.grudge-studio.com",
    repo: "gameopen",
    engine: "React + Three.js",
    status: "live",
    category: "tool",
    topics: ["launcher", "library", "hub"],
    thumbnail: THUMB("gameopen"),
    hasServer: true,
  },
  {
    id: "character-foundry",
    name: "grudge-character-animator",
    displayName: "Character Foundry",
    description: "Create heroes + 4-slot select — handoff to client live play.",
    url: "https://character.grudge-studio.com",
    repo: "grudge-character-animator",
    engine: "React + Three.js",
    status: "live",
    category: "tool",
    topics: ["characters", "create", "foundry"],
    thumbnail: THUMB("grudge-character-animator"),
    hasServer: true,
  },
  {
    id: "client-play",
    name: "Grudge-Builder",
    displayName: "Warlords Client (Live Play)",
    description: "Home island / zone / lobby / world — production play funnel.",
    url: "https://client.grudge-studio.com",
    repo: "Grudge-Builder",
    engine: "React + Three.js + Phaser",
    status: "live",
    category: "rpg",
    topics: ["rpg", "mmo", "play"],
    thumbnail: THUMB("Grudge-Builder"),
    hasServer: true,
  },
  {
    id: "grudgewarlords",
    name: "Grudge-Warlords",
    displayName: "Grudge Warlords",
    description: "Main MMO marketing + client shell — island crafting, sailing, cNFT.",
    url: "https://grudgewarlords.com",
    repo: "Grudge-Builder",
    engine: "React + Three.js + Phaser",
    status: "live",
    category: "rpg",
    topics: ["rpg", "mmo", "crafting"],
    thumbnail: THUMB("Grudge-Builder"),
    hasServer: true,
    releasesUrl: "https://github.com/MolochDaGod/Grudge-Builder/releases",
  },
  {
    id: "tactical-infinity",
    name: "Tactical-Infinity",
    displayName: "Warlords Water / Home Island",
    description:
      "Warlords home-island + open water sailing (TI repo legacy name). Production only — not tactical-infinity.vercel.app.",
    url: "https://water.grudge-studio.com",
    repo: "Tactical-Infinity",
    engine: "Three.js + R3F",
    status: "live",
    category: "rpg",
    topics: ["island", "sailing", "water", "warlords"],
    thumbnail: THUMB("Tactical-Infinity"),
    hasServer: true,
  },
  {
    id: "grudox",
    name: "grudox",
    displayName: "GRUDOX Hub",
    description: "Fleet hub + Carrier / space / brawl rooms (CF edge → Railway).",
    url: "https://grudox.grudge-studio.com",
    repo: "gameopen",
    engine: "Vite + CF Worker",
    status: "live",
    category: "action",
    topics: ["pvp", "carrier", "hub"],
    thumbnail: THUMB("gameopen"),
    hasServer: true,
  },
  {
    id: "studio-forge",
    name: "RTS-Grudge",
    displayName: "Grudge Studio Forge",
    description: "Fleet map & model editor — terrain, ObjectStore CDN, play mode. Warlords · RTS · DCQ.",
    url: "https://forge.grudge-studio.com",
    repo: "RTS-Grudge",
    engine: "R3F + Rapier + drei",
    status: "live",
    category: "tool",
    topics: ["tool", "editor", "3d"],
    thumbnail: THUMB("RTS-Grudge"),
  },
  {
    id: "grudge-pipeline",
    name: "grudge-pipeline",
    displayName: "Grudge Pipeline",
    description:
      "Asset ingest → bake → optimize → R2 → open in Forge. Production tool at grudge-pipeline.vercel.app (postMessage scene pack to forge.grudge-studio.com).",
    url: "https://grudge-pipeline.vercel.app",
    repo: "grudge-pipeline",
    engine: "Vite + Three.js",
    status: "live",
    category: "tool",
    topics: ["tool", "pipeline", "assets", "bake", "forge"],
    thumbnail: THUMB("grudge-pipeline"),
  },
  {
    id: "rts-grudge",
    name: "RTS-Grudge",
    displayName: "RTS Grudge",
    description: "Real-time strategy with R3F + Rapier physics and fleet characters.",
    url: "https://rts-grudge.vercel.app",
    repo: "RTS-Grudge",
    engine: "R3F + Rapier",
    status: "live",
    category: "rts",
    topics: ["rts", "action"],
    thumbnail: THUMB("RTS-Grudge"),
    hasServer: true,
  },
  {
    id: "grudges-survival",
    name: "survival",
    displayName: "Grudges Survival",
    description: "Open-world survival — harvest, build, fight in 3D.",
    url: "https://grudges.grudge-studio.com",
    repo: "survival",
    engine: "R3F + Rapier",
    status: "active",
    category: "rpg",
    topics: ["rpg", "survival"],
    thumbnail: THUMB("survival"),
    hasServer: true,
  },
  {
    id: "grudge-drive",
    name: "grudge-drive",
    displayName: "Grudge Drive",
    description: "Racing prototype — Three.js fleet stack.",
    url: "https://drive.grudge-studio.com",
    repo: "grudge-drive",
    engine: "Three.js",
    status: "active",
    category: "racing",
    topics: ["racing", "demo"],
    thumbnail: THUMB("grudge-drive"),
  },
  {
    id: "grudge-arena",
    name: "grudge-arena",
    displayName: "Grudge Arena",
    description: "Three.js arena combat with Socket.IO multiplayer.",
    url: "https://arena.grudge-studio.com",
    repo: "grudge-arena",
    engine: "Three.js",
    status: "active",
    category: "action",
    topics: ["action", "pvp"],
    thumbnail: THUMB("grudge-arena"),
    hasServer: true,
  },
  {
    id: "arena-bridge",
    name: "grudge-arena-bridge",
    displayName: "Arena Bridge (WoW)",
    description: "WoW bridge client for cross-game arena events.",
    url: "https://wow.grudge-studio.com",
    repo: "grudge-arena-bridge",
    engine: "Web",
    status: "active",
    category: "action",
    topics: ["action"],
    thumbnail: THUMB("grudge-arena-bridge"),
  },
  {
    id: "grim-armada",
    name: "grim-armada-web",
    displayName: "Grim Armada",
    description: "Naval strategy — fleet battles in Three.js.",
    url: "https://armada.grudge-studio.com",
    repo: "grim-armada-web",
    engine: "Three.js + React",
    status: "active",
    category: "rts",
    topics: ["rts", "action"],
    thumbnail: THUMB("grim-armada-web"),
  },
  {
    id: "dungeon-crawler",
    name: "Dungeon-Crawler-Quest",
    displayName: "Dungeon Crawler Quest",
    description: "Voxel dungeon crawler — procedural rooms and loot.",
    url: "https://dcq.grudge-studio.com",
    repo: "Dungeon-Crawler-Quest",
    engine: "Three.js + Voxel + Rapier",
    status: "active",
    category: "rpg",
    topics: ["rpg", "dungeon"],
    thumbnail: THUMB("Dungeon-Crawler-Quest"),
  },
  {
    id: "grudge-space-rts",
    name: "GrudgeSpaceRTS",
    displayName: "GrudgeSpace RTS / Mech PvP",
    description: "Space RTS + mech PvP playground (Three.js fleet combat).",
    url: "https://grudge-space-rts.vercel.app",
    repo: "GrudgeSpaceRTS",
    engine: "Three.js",
    status: "active",
    category: "rts",
    topics: ["rts", "space", "pvp"],
    thumbnail: THUMB("GrudgeSpaceRTS"),
  },
  {
    id: "mech-forge",
    name: "grudge-mech-forge",
    displayName: "Grudge Mech Forge",
    description: "Mech builder playground — R3F + Rapier test rig.",
    url: "https://mech-playground.vercel.app",
    repo: "grudge-mech-forge",
    engine: "R3F + Rapier",
    status: "active",
    category: "demo",
    topics: ["demo", "mech"],
    thumbnail: THUMB("grudge-mech-forge"),
  },
  {
    id: "metaverse",
    name: "grudge-metaverse",
    displayName: "Grudge Metaverse",
    description: "Metaverse avatars and social space — grudge6 fleet characters.",
    url: "https://metaverse.grudge-studio.com",
    repo: "grudge-metaverse",
    engine: "Three.js",
    status: "active",
    category: "rpg",
    topics: ["metaverse", "avatars"],
    thumbnail: THUMB("grudge-metaverse"),
  },
  {
    id: "studio-editor",
    name: "grudge-studio",
    displayName: "Studio Editor",
    description: "Browser studio editor artifact — scenes, nature packs, playtests.",
    url: "https://studio.grudge-studio.com",
    repo: "grudge-studio",
    engine: "R3F",
    status: "active",
    category: "tool",
    topics: ["tool", "editor"],
    thumbnail: THUMB("grudge-studio"),
  },
  {
    id: "character-creator",
    name: "grudge-character-creator",
    displayName: "Character Creator (legacy)",
    description: "Legacy 3D equipment tester — prefer Character Foundry.",
    url: "https://playground-teal-zeta.vercel.app",
    repo: "grudge-character-creator",
    engine: "Three.js",
    status: "active",
    category: "tool",
    topics: ["tool", "characters", "legacy"],
    thumbnail: THUMB("grudge-character-creator"),
  },
  {
    id: "final-fighter",
    name: "FinalFighter",
    displayName: "Final Fighter",
    description: "Arcade fighter prototype.",
    url: "https://final-fighter.vercel.app",
    repo: "FinalFighter",
    engine: "Three.js",
    status: "active",
    category: "action",
    topics: ["action", "fighting"],
    thumbnail: THUMB("FinalFighter"),
  },
  {
    id: "wcs",
    name: "grudge-wcs",
    displayName: "WCS (Betta Warlords)",
    description: "Warlord Crafting Suite shell — character + island UI.",
    url: "https://wcs.grudge-studio.com",
    repo: "grudge-wcs",
    engine: "Web",
    status: "active",
    category: "tool",
    topics: ["tool", "crafting"],
    thumbnail: THUMB("grudge-wcs"),
  },
  {
    id: "grudgeworld",
    name: "GrudgeWorld-Action-RPG",
    displayName: "GrudgeWorld Action RPG (archive)",
    description: "Legacy Babylon ARPG — dead deploy; prefer Open / client play. Not a production play target.",
    url: "https://open.grudge-studio.com",
    repo: "GrudgeWorld-Action-RPG",
    engine: "Babylon (archive)",
    status: "planned",
    category: "rpg",
    topics: ["archive", "legacy"],
    thumbnail: THUMB("GrudgeWorld-Action-RPG"),
  },
  {
    id: "the-engine",
    name: "The-ENGINE",
    displayName: "The ENGINE (Portal)",
    description: "Grudge Studio portal shell — fleet hub and docs.",
    url: "https://grudge-studio.com",
    repo: "The-ENGINE",
    engine: "Vite",
    status: "live",
    category: "tool",
    topics: ["tool", "portal"],
    thumbnail: THUMB("The-ENGINE"),
  },
  {
    id: "grudgecontrol",
    name: "grudgecontrol",
    displayName: "Grudge Control",
    description: "Fleet control panel — grudge6 showcase and systems map.",
    url: "https://grudgecontrol.vercel.app",
    repo: "grudgecontrol",
    engine: "React",
    status: "active",
    category: "tool",
    topics: ["tool", "admin"],
    thumbnail: THUMB("grudgecontrol"),
  },
  {
    id: "grudgedot",
    name: "grudgedot",
    displayName: "grudgedot Launcher",
    description:
      "Planned desktop launcher — Vercel URL not live (404). Prefer Open launcher until redeployed.",
    url: "https://open.grudge-studio.com",
    repo: "grudgedot",
    engine: "Web",
    status: "planned",
    category: "tool",
    topics: ["tool", "launcher"],
    thumbnail: THUMB("grudgedot"),
  },
  {
    id: "fresh-grudge",
    name: "FRESH-GRUDGE",
    displayName: "FRESH GRUDGE",
    description: "Unity mobile action game on Google Play.",
    url: "https://play.google.com/store/apps/details?id=com.grudgestudio.freshgrudge",
    repo: "FRESH-GRUDGE",
    engine: "Unity",
    status: "active",
    category: "mobile",
    topics: ["mobile", "action"],
    thumbnail: THUMB("FRESH-GRUDGE"),
  },
  {
    id: "grudaagent",
    name: "grudge-agent",
    displayName: "GRUDA Agent",
    description: "Agentic AI workspace — private projects, Legion hub, Forge/Coder bridge.",
    url: "https://ai.grudge-studio.com",
    repo: "grudge-ai-hub",
    engine: "Cloudflare Workers + GRUDA",
    status: "live",
    category: "tool",
    topics: ["tool", "ai", "agent"],
    thumbnail: THUMB("grudge-ai-hub"),
  },
];

/** Verified storefront asset categories on assets.grudge-studio.com / ObjectStore. */
export interface StoreCategory {
  id: string;
  label: string;
  icon: string;
  prefix: string;
  objectStorePath?: string;
}

export const STORE_CATEGORIES: StoreCategory[] = [
  { id: "master", label: "All Fleet Items", icon: "🗂️", prefix: "models/", objectStorePath: "master-items.json" },
  { id: "era-taxonomy", label: "Era Taxonomy (SSOT)", icon: "🗺️", prefix: "models/", objectStorePath: "era-asset-taxonomy.json" },
  { id: "era-characters", label: "Characters by Era", icon: "👥", prefix: "models/grudge6/", objectStorePath: "era-characters.json" },
  { id: "warlords", label: "Warlords Era (fantasy)", icon: "⚔️", prefix: "models/grudge6/", objectStorePath: "warlords-catalog.json" },
  { id: "warlords-sectors", label: "Warlords 9 Sectors", icon: "🧭", prefix: "models/environment/sectors/", objectStorePath: "warlords-zones.json" },
  { id: "home-island", label: "Home Island Assets", icon: "🏝️", prefix: "models/nature/", objectStorePath: "home-island-contract.json" },
  { id: "nexus", label: "Nexus Era (modern)", icon: "🏙️", prefix: "models/nexus/", objectStorePath: "era-characters.json" },
  { id: "armada", label: "Armada Era (sci-fi)", icon: "🚀", prefix: "grudge-armada/", objectStorePath: "grudge-armada.json" },
  { id: "voxel", label: "Voxel Style", icon: "🧱", prefix: "models/voxel/", objectStorePath: "voxelAssets.json" },
  { id: "recipes", label: "Crafting Recipes", icon: "📜", prefix: "models/", objectStorePath: "master-recipes.json" },
  { id: "weapons", label: "Weapons & Guns", icon: "⚔️", prefix: "models/weapons/", objectStorePath: "weapons.json" },
  { id: "characters", label: "Characters (legacy path)", icon: "🧙", prefix: "models/characters/", objectStorePath: "era-characters.json" },
  { id: "ships", label: "Ships & Vehicles", icon: "🚢", prefix: "models/ships/", objectStorePath: "ships.json" },
  { id: "environment", label: "Nature & Environment", icon: "🌲", prefix: "models/environment/", objectStorePath: "organized-nature-manifest.json" },
  // buildings.json is not always published — fall back to home-island contract / R2 prefix browse
  { id: "buildings", label: "Buildings & Scenes", icon: "🏰", prefix: "models/buildings/", objectStorePath: "home-island-contract.json" },
  { id: "sprites-2d", label: "2D Character Sprites", icon: "🖼️", prefix: "sprites/", objectStorePath: "sprite-characters.json" },
  { id: "effects-2d", label: "2D Effects / VFX", icon: "✨", prefix: "effects/", objectStorePath: "effects-registry.json" },
  { id: "icons", label: "2D Icons", icon: "🎨", prefix: "icons/", objectStorePath: "icon-registry.json" },
  { id: "ui-2d", label: "2D UI / Fonts", icon: "🪟", prefix: "ui/", objectStorePath: "ui-packs.json" },
  { id: "vfx", label: "VFX & Particles", icon: "💫", prefix: "vfx/", objectStorePath: "vfx-pipeline.json" },
  { id: "audio", label: "Audio", icon: "🔊", prefix: "audio/", objectStorePath: "audio.json" },
  { id: "scenes", label: "Scene Editors", icon: "🎬", prefix: "scenes/", objectStorePath: undefined },
  { id: "asset-packs", label: "Asset Packs", icon: "📦", prefix: "asset-packs/", objectStorePath: undefined },
  { id: "media-types", label: "Media Types Map", icon: "📚", prefix: "icons/", objectStorePath: "asset-media-types.json" },
];