import assert from 'node:assert/strict';
import * as THREE from 'three';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { bindRequestedActions, fitDefaultAssembly, validateCreationPromptPlan } from '../src/main/prompt3d/creationPrompt';
import { submitCreation, saveCreationToLibrary, reopenCreation } from '../src/main/prompt3d/creationService';
import { creationIO, createOriginalGeometry, enhanceOriginalGeometry, adjustOriginalGeometry } from '../src/main/prompt3d/proceduralCreation';
import { serializeScene, parseSceneJson } from '../src/renderer/lib/forge/sceneSerializer';
import { DEFAULT_BODY_MORPH } from '../src/renderer/lib/forge/boneAliases';
import { DEFAULT_FORGE_ANIM } from '../src/renderer/lib/forge/forgeAnimation';
import { applyCreationEdit, creationSceneHash, validateCreationEdit } from '../src/main/prompt3d/creationEdits';
import { addOriginalMotion, originalGeometryHash } from '../src/main/prompt3d/proceduralCreation';
import { bindLiteralCreationEdit } from '../src/main/prompt3d/creationLiteralEdits';

async function main(){
  const request={prompt:'Create a blue cube, spin it, and save it',category:'prop' as const,style:'low-poly' as const,usePlanner:true};
  const incomplete={kind:'box',summary:'Fixture proposal',unsupported:[],steps:[{operation:'create',instruction:'Create a box'}],components:[]};
  const bound=validateCreationPromptPlan(await bindRequestedActions(incomplete,request));
  assert.deepEqual(bound.steps.map(s=>s.operation),['create','texture','turntable','save'],'No requested action can disappear');
  const irrelevantLimitations=validateCreationPromptPlan(await bindRequestedActions({...incomplete,unsupported:['person','assembly','existing-asset']},request));
  assert.deepEqual(irrelevantLimitations.steps.map(s=>s.operation),['create','texture','turntable','save'],'Unrequested supported-kind names are not unavailable user actions');
  const negated=validateCreationPromptPlan(await bindRequestedActions({...incomplete,steps:[...incomplete.steps,{operation:'turntable',instruction:'Spin it'}]}, {...request,prompt:'Create a blue cube without animation and save it'}));
  assert.ok(!negated.steps.some(s=>s.operation==='turntable'),'Unrequested model motion is removed');
  const plain=validateCreationPromptPlan(await bindRequestedActions({...incomplete,steps:[...incomplete.steps,{operation:'texture',instruction:'Paint black'},{operation:'save',instruction:'Save'}]}, {...request,prompt:'Create a cube. Do not spin it.'}));
  assert.deepEqual(plain.steps.map(s=>s.operation),['create'],'Plain creation cannot invent surface or save steps');
  const editProposal={...incomplete,steps:[{operation:'edit',instruction:'Rotate it 90 degrees around Y',edit:{action:'rotate',targets:['$asset'],value:[0,90,0]}},{operation:'save',instruction:'Save'}]};
  const rotation=validateCreationPromptPlan(await bindRequestedActions(editProposal,{...request,prompt:'Rotate it 90 degrees around Y and save it.'},'box'),'box');
  assert.deepEqual(rotation.steps.map(s=>s.operation),['edit','save']);
  const wrongTarget=structuredClone(editProposal);wrongTarget.steps[0].edit!.targets=['box'];
  const correctTarget=validateCreationPromptPlan(await bindRequestedActions(wrongTarget,{...request,prompt:'Rotate it 90 degrees around Y and save it'},'box'),'box');
  assert.deepEqual(correctTarget.steps[0].edit?.targets,['$asset'],'It always means the whole selected asset');
  assert.deepEqual(bindLiteralCreationEdit({action:'move',targets:['Tree 2 crown'],value:[2,0,0]},'Move Tree 2 crown two metres forward').value,[0,0,2]);
  assert.deepEqual(bindLiteralCreationEdit({action:'move',targets:['$asset'],value:[1,0,0]},'Shift it left by 50 cm').value,[-.5,0,0]);
  assert.deepEqual(bindLiteralCreationEdit({action:'scale',targets:['$asset'],value:[2,1,1]},'Make it 25% wider').value,[1.25,1,1]);
  const preserved=validateCreationPromptPlan(await bindRequestedActions({...incomplete,steps:[{operation:'texture',instruction:'Paint blue'},{operation:'save',instruction:'Save'}]},{...request,prompt:'Keep its blue color and save it'},'box'),'box');
  assert.deepEqual(preserved.steps.map(s=>s.operation),['save'],'Preserve clauses do not authorize recoloring');
  const partContext:any={parts:[{name:'Tree 1 crown',mesh:true},{name:'Tree 2 crown',mesh:true}],clips:[]};
  const substituted={kind:'assembly',summary:'test',unsupported:[],steps:[{operation:'edit',instruction:'Color crown',edit:{action:'color',targets:['Tree 1 crown'],color:'#ff0000'}},{operation:'save',instruction:'Save'}],components:[]};
  await assert.rejects(()=>bindRequestedActions(substituted,{...request,prompt:'Make only Tree 99 crown red and save it'},'assembly',partContext),/does not exist/);
  const corrected=validateCreationPromptPlan(await bindRequestedActions(substituted,{...request,prompt:'Make only Tree 2 crown red and save it'},'assembly',partContext),'assembly');
  assert.deepEqual(corrected.steps[0].edit?.targets,['Tree 2 crown'],'An explicit part name cannot be substituted');
  const wrongKind=validateCreationPromptPlan(await bindRequestedActions({...substituted,kind:'cone'},{...request,prompt:'Make only Tree 2 crown red and save it'},'assembly',partContext),'assembly');
  assert.equal(wrongKind.kind,'assembly','Selecting one part does not change the current asset kind');
  const successive={...incomplete,steps:[{operation:'edit',instruction:'Move right',edit:{action:'move',targets:['$asset'],value:[1,0,0]}},{operation:'edit',instruction:'Move up',edit:{action:'move',targets:['$asset'],value:[1,0,0]}},{operation:'save',instruction:'Save'}]};
  const successivePlan=validateCreationPromptPlan(await bindRequestedActions(successive,{...request,prompt:'Move it one metre right, then move it two metres up and save it'},'box'),'box');
  assert.deepEqual(successivePlan.steps.filter(s=>s.edit).map(s=>s.edit!.value),[[1,0,0],[0,2,0]],'Each repeated action binds its own clause');
  await assert.rejects(()=>bindRequestedActions({...incomplete,steps:[{operation:'save',instruction:'Save'}]},{...request,prompt:'Move it two metres right and save it'},'box'),/did not resolve/);
  assert.throws(()=>validateCreationEdit({action:'move',targets:['$asset'],value:[Infinity,0,0]}),/Invalid edit/);
  assert.throws(()=>validateCreationEdit({action:'color',targets:['box','box'],color:'#ff0000'}),/unique/);
  assert.throws(()=>validateCreationPromptPlan({...incomplete,unsupported:['Generate a functioning game']}),/unsupported work/);
  assert.throws(()=>validateCreationPromptPlan({...incomplete,steps:[{operation:'dance',instruction:'Dance'}]},'box'),/not supported/);
  assert.throws(()=>validateCreationPromptPlan({...incomplete,steps:[{operation:'adjust',instruction:'Scale',adjustments:{scaleX:Infinity}}]},'box'),/bounded adjustment/);
  const root=await mkdtemp(join(tmpdir(),'grudge-prompt-build-'));
  const components=[{name:'Ground',shape:'plane' as const,position:[0,0,0] as [number,number,number],size:[10,1,10] as [number,number,number],color:'#33aa44'}, {name:'Pillar',shape:'box' as const,position:[0,1,0] as [number,number,number],size:[1,2,1] as [number,number,number],color:'#999999'}];
  const plan=validateCreationPromptPlan({...incomplete,kind:'assembly',components});
  const tree=fitDefaultAssembly({...plan,components:[components[0],{...components[1],name:'trunk',shape:'cylinder',position:[20,7,0]}, {...components[1],name:'crown',shape:'cone',position:[20,7,1]}]},'Build a world with one tree and ground');
  assert.equal(tree.components[1].position[1]-tree.components[1].size[1]/2,0,'Trunk is grounded');
  assert.deepEqual([tree.components[1].position[0],tree.components[1].position[2]],[tree.components[2].position[0],tree.components[2].position[2]],'Crown sits on its trunk');
  assert.ok(tree.components[2].position[1]-tree.components[2].size[1]/2<tree.components[1].size[1],'Crown overlaps trunk instead of floating');
  assert.ok(tree.components[0].size[2]>=12,'Ground has actual horizontal depth');
  const asset=await submitCreation(root,{...request,prompt:'DEVELOPMENT FIXTURE assembly',usePlanner:false},{...plan,operation:'create',planner:'test fixture, no inference',constraints:[]});
  assert.equal(asset.state,'complete',asset.message);
  const saved=await saveCreationToLibrary(root,asset.id),reopened=await reopenCreation(root,asset.id);
  assert.equal(saved.asset.sha256,reopened.sha256);
  const doc=await(await creationIO()).read(saved.asset.savedPath);
  assert.equal(doc.getRoot().listMeshes().length,2);
  const materials=doc.getRoot().listMaterials();
  assert.notDeepEqual(materials[0].getBaseColorFactor(),materials[1].getBaseColorFactor(),'Assembly colors reach actual materials');
  const geometryBefore=originalGeometryHash(doc),sceneBefore=creationSceneHash(doc);
  applyCreationEdit(doc,{action:'move',targets:['$asset'],value:[2,0,0]});
  applyCreationEdit(doc,{action:'rotate',targets:['$asset'],value:[0,90,0]});
  applyCreationEdit(doc,{action:'scale',targets:['$asset'],value:[2,1,1]});
  const placement=doc.getRoot().listNodes().find((n:any)=>n.getExtras().promptPlacement);
  assert.deepEqual(placement.getTranslation(),[2,0,0]);assert.deepEqual(placement.getScale(),[2,1,1]);
  assert.ok(Math.abs(placement.getRotation()[1]-Math.SQRT1_2)<1e-6);
  assert.equal(originalGeometryHash(doc),geometryBefore,'Static transforms preserve underlying meshes');
  assert.notEqual(creationSceneHash(doc),sceneBefore,'Scene changes have their own measured identity');
  const groundMaterial=doc.getRoot().listNodes().find((n:any)=>n.getName()==='Ground').getMesh().listPrimitives()[0].getMaterial();
  const groundColor=[...groundMaterial.getBaseColorFactor()];
  applyCreationEdit(doc,{action:'color',targets:['Pillar'],color:'#ff0000'});
  assert.deepEqual(groundMaterial.getBaseColorFactor(),groundColor,'Part color preserves unselected surfaces');
  assert.throws(()=>applyCreationEdit(doc,{action:'move',targets:['Missing tree'],value:[1,0,0]}),/missing/);
  assert.throws(()=>applyCreationEdit(doc,{action:'scale',targets:['$asset'],value:[1,1,1]}),/no change/);
  const animated=createOriginalGeometry({kind:'box',operation:'create',summary:'test',constraints:[],planner:'fixture'},'low-poly');
  addOriginalMotion(animated,{kind:'box',operation:'turntable',summary:'test',constraints:[],planner:'fixture'});
  applyCreationEdit(animated,{action:'rotate',targets:['$asset'],value:[0,90,0]});
  const channel=animated.getRoot().listAnimations()[0].listChannels()[0];
  assert.notEqual(channel.getTargetNode(),animated.getRoot().getDefaultScene().listChildren()[0],'Animation cannot override static placement');
  applyCreationEdit(animated,{action:'clear-animation',targets:['$asset']});
  assert.equal(animated.getRoot().listAnimations().length,0);
  const edited=await submitCreation(root,{...request,parentId:asset.id,prompt:'Fixture static translation',usePlanner:false},{kind:'assembly',operation:'edit',edit:{action:'move',targets:['$asset'],value:[2,0,0]},summary:'Fixture move',constraints:[],planner:'fixture'});
  assert.equal(edited.state,'complete',edited.message);assert.notEqual(edited.sceneHash,edited.previousSceneHash);
  assert.equal((await reopenCreation(root,edited.id)).sha256,(await saveCreationToLibrary(root,edited.id)).asset.sha256);
  // A native replay exposed a floating inlay and a blade pulled out of its guard.
  for(const curved of [false,true]){
    const swordPlan:any={kind:'sword',operation:'create',curved,constraints:[],summary:'Decoration fit regression'};
    const sword=createOriginalGeometry(swordPlan,'low-poly');
    enhanceOriginalGeometry(sword,swordPlan);
    adjustOriginalGeometry(sword,{...swordPlan,operation:'adjust',adjustments:{bladeLength:1.25,bladeWidth:1.2,curveDelta:.12}});
    const nodes=sword.getRoot().listNodes(),blade=nodes.find((n:any)=>n.getName()==='Blade').getMesh().listPrimitives()[0].getAttribute('POSITION').getArray();
    const rows:Array<{x:number;y:number}>=[];
    for(let row=0;row<40;row++){let x=0,y=0;for(let i=0;i<8;i++){x+=blade[(row*8+i)*3];y+=blade[(row*8+i)*3+1];}rows.push({x:x/8,y:y/8});}
    assert.ok(Math.abs(rows[0].y-.28)<1e-6,'Resizing keeps the blade seated in its guard');
    const inlay=nodes.find((n:any)=>/^BladeFullerInlayDetail/.test(n.getName())).getMesh().listPrimitives()[0].getAttribute('POSITION').getArray();
    for(let i=0;i<inlay.length;i+=3){
      const y=inlay[i+1],high=rows.findIndex(row=>row.y>=y),a=rows[Math.max(0,high-1)],b=rows[Math.max(0,high)];
      const t=b.y>a.y?(y-a.y)/(b.y-a.y):0,center=a.x+(b.x-a.x)*t;
      assert.ok(Math.abs(inlay[i]-center)<.004,'The decorative inlay follows the actual resized curved blade');
    }
  }
  const mesh=new THREE.Mesh(new THREE.BoxGeometry(1,2,3),new THREE.MeshStandardMaterial({color:0x2255dd}));mesh.name='Edited primitive';mesh.position.set(3,1,2);
  const mixer=new THREE.AnimationMixer(mesh);mesh.userData.grudgeMixer=mixer;
  const clip=new THREE.AnimationClip('Spin',2,[new THREE.NumberKeyframeTrack('.rotation[y]',[0,2],[0,Math.PI*2])]);
  const scene=serializeScene({name:'Retained primitives',entities:[{id:'one',name:mesh.name,format:'primitive',object:mesh,diskPath:null,bodyMorph:{...DEFAULT_BODY_MORPH},animations:[clip]}],background:0,showHelpers:true,animSettings:DEFAULT_FORGE_ANIM,camera:new THREE.PerspectiveCamera(),controlsTarget:new THREE.Vector3(),lights:{} as any});
  assert.equal(mesh.userData.grudgeMixer,mixer,'Serialization preserves live runtime references');
  const parsed=parseSceneJson(JSON.stringify(scene));
  const restored=new THREE.ObjectLoader().parse(parsed.entities[0].embedded!);
  assert.deepEqual(restored.position.toArray(),[3,1,2]);
  assert.equal((restored as THREE.Mesh).geometry.getAttribute('position').count,24);
  assert.equal(THREE.AnimationClip.parse(parsed.entities[0].clips![0]).name,'Spin');
  assert.equal((restored as THREE.Mesh).material instanceof THREE.MeshStandardMaterial,true);
  console.log(JSON.stringify({passed:true,root,assembly:asset.assetPath,sceneRoundTrip:true,actionCoverage:true}));
}
main().catch(e=>{console.error(e);process.exitCode=1;});
