import type { Prompt3DProviderManifest } from "../../shared/prompt3d";

const GiB = 1024 ** 3;

export const PROMPT3D_PROVIDERS: Prompt3DProviderManifest[] = [
  {
    id: "hunyuan3d-2",
    name: "Hunyuan3D 2.1",
    kind: "local",
    summary: "Official Hunyuan image-conditioned shape and paint pipeline, with an explicit local concept-image stage for text prompts.",
    routes: ["concept-image-to-3d", "image-to-3d"],
    enabledRoutes: ["concept-image-to-3d"],
    geometry: "Hunyuan3D-DiT 2.1 shape generation; strongest MVP path is prompt → concept image → geometry.",
    textures: "Official Hunyuan3D-Paint 2.1 texture synthesis.",
    outputFormats: ["GLB", "OBJ"],
    qualitySpeed: "Good detailed props and environments; texture generation adds substantial VRAM and runtime.",
    platform: "The upstream source declares Windows, Linux and macOS support. This build's reproducible Windows-host path is explicitly normal-user WSL2 because the upstream Python 3.10 dependency set pins an unavailable bpy 4.0 wheel; other host integrations are not enabled.",
    sourceUrl: "https://github.com/Tencent-Hunyuan/Hunyuan3D-2.1",
    sourceRevision: "82920d643c0dc2f7bfd7255f45f62d386edfe60c",
    modelSources: [
      {
        id: "tencent/Hunyuan3D-2.1", revision: "0b94677654c57bb9a6b6845cd7b704ccf551d327",
        estimatedDownloadBytes: 13_890_000_000, purpose: "Hunyuan3D 2.1 shape and PBR paint checkpoints",
      },
      {
        id: "Tencent-Hunyuan/HunyuanDiT-v1.1-Diffusers-Distilled", revision: "527cf2ecce7c04021975938f8b0e44e35d2b1ed9",
        estimatedDownloadBytes: 13_500_000_000, purpose: "Local prompt-to-concept-image stage",
      },
      {
        id: "facebook/dinov2-giant", revision: "611a9d42f2335e0f921f1e313ad3c1b7178d206d",
        estimatedDownloadBytes: 4_546_010_000, purpose: "Official DINOv2 image encoder required by Hunyuan3D-Paint",
        allowPatterns: ["*.json", "*.safetensors"],
      },
    ],
    sourceDependencies: [],
    licenseName: "Tencent Hunyuan 3D 2.1 Community License (territory and use restrictions apply)",
    licenseUrl: "https://github.com/Tencent-Hunyuan/Hunyuan3D-2.1/blob/main/LICENSE",
    downloadBytes: 45 * GiB,
    installedBytes: 80 * GiB,
    requiredFreeDiskBytes: 95 * GiB,
    physicalVramBytes: 21 * GiB,
    minimumWindowsNvidiaDriver: "551.61",
    runVramBytes: { geometry: 10 * GiB, textured: 21 * GiB, reducedGeometry: 10 * GiB },
    systemRamBytes: 32 * GiB,
    requiredComponents: [
      "uv 0.12.7 (checksum pinned)",
      "normal WSL2 Ubuntu user distribution on Windows hosts",
      "isolated Python 3.11 compatibility environment (upstream bpy 4.0/CPython 3.10 wheel is unavailable)",
      "PyTorch 2.5.1 CUDA 12.4 runtime and isolated CUDA build toolkit",
      "NVIDIA Windows driver 551.61 or newer (CUDA 12.4 GA requirement)",
      "official Hunyuan3D-2.1 source at pinned commit",
      "Hunyuan3D 2.1 shape/paint weights at pinned revision",
      "HunyuanDiT distilled concept-image weights at pinned revision",
      "sentencepiece 0.2.1 tokenizer runtime required by the HunyuanDiT concept-image stage",
      "official DINOv2 giant image encoder at pinned revision (safetensors only)",
      "checksum-pinned RealESRGAN x4plus texture helper weight",
    ],
  },
  {
    id: "trellis",
    name: "Microsoft TRELLIS",
    kind: "local",
    summary: "Official Microsoft structured 3D latent pipeline. Direct text is available; the recommended higher-detail path uses a concept image then image-conditioned TRELLIS.",
    routes: ["direct-text", "image-to-3d"],
    enabledRoutes: ["direct-text"],
    geometry: "Structured latent mesh plus radiance/3D Gaussian representation.",
    textures: "GLB conversion bakes appearance from the generated representation; topology still needs validation.",
    outputFormats: ["GLB", "PLY"],
    qualitySpeed: "Direct text is simpler but less detailed; concept-image conditioning is usually more creative and detailed.",
    platform: "Officially Linux-tested only. Windows uses a normal user WSL2 Ubuntu distribution; Docker's internal distro is rejected.",
    sourceUrl: "https://github.com/microsoft/TRELLIS",
    sourceRevision: "442aa1e1afb9014e80681d3bf604e8d728a86ee7",
    modelSources: [
      {
        id: "microsoft/TRELLIS-text-xlarge", revision: "e0b00432b8e3a8ecee0df806ab1df9f7281f2be4",
        estimatedDownloadBytes: 3_840_000_000, purpose: "Direct text-to-structured-3D model",
      },
      {
        id: "microsoft/TRELLIS-image-large", revision: "25e0d31ffbebe4b5a97464dd851910efc3002d96",
        estimatedDownloadBytes: 3_070_000_000, purpose: "Shared decoders and image-conditioned TRELLIS model",
      },
      {
        id: "openai/clip-vit-large-patch14", revision: "32bd64288804d66eefd0ccbe215aa642df71cc41",
        estimatedDownloadBytes: 1_714_300_000, purpose: "Text conditioning required by TRELLIS text-xlarge",
        allowPatterns: ["*.json", "*.txt", "*.safetensors"],
      },
    ],
    sourceDependencies: [
      {
        id: "utils3d", sourceUrl: "https://github.com/EasternJournalist/utils3d.git",
        revision: "9a4eb15e4021b67b12c460c7057d642626897ec8", purpose: "TRELLIS mesh and camera utilities",
        licenseUrl: "https://github.com/EasternJournalist/utils3d/blob/9a4eb15e4021b67b12c460c7057d642626897ec8/LICENSE",
      },
      {
        id: "nvdiffrast", sourceUrl: "https://github.com/NVlabs/nvdiffrast.git",
        revision: "253ac4fcea7de5f396371124af597e6cc957bfae", purpose: "CUDA mesh rasterization used by GLB texture baking",
        licenseUrl: "https://github.com/NVlabs/nvdiffrast/blob/253ac4fcea7de5f396371124af597e6cc957bfae/LICENSE.txt",
      },
      {
        id: "mip-splatting", sourceUrl: "https://github.com/autonomousvision/mip-splatting.git",
        revision: "dda02ab5ecf45d6edb8c540d9bb65c7e451345a9", purpose: "Pinned Gaussian rasterizer used by TRELLIS appearance baking",
        licenseUrl: "https://github.com/autonomousvision/mip-splatting/blob/dda02ab5ecf45d6edb8c540d9bb65c7e451345a9/LICENSE.md",
      },
      {
        id: "vox2seq", sourceUrl: "https://github.com/microsoft/TRELLIS.git",
        revision: "f17fdf12d8f17a6a09225f01756d141285dc848f", purpose: "Serialized sparse-attention extension removed from current TRELLIS source but still required by its pipeline",
        licenseUrl: "https://github.com/microsoft/TRELLIS/blob/f17fdf12d8f17a6a09225f01756d141285dc848f/LICENSE",
        installSubpath: "extensions/vox2seq",
      },
    ],
    licenseName: "MIT (repository/model; bundled submodules retain their own licenses)",
    licenseUrl: "https://github.com/microsoft/TRELLIS/blob/main/LICENSE",
    downloadBytes: 26 * GiB,
    installedBytes: 48 * GiB,
    requiredFreeDiskBytes: 65 * GiB,
    physicalVramBytes: 16 * GiB,
    minimumWindowsNvidiaDriver: "531.14",
    runVramBytes: { geometry: 16 * GiB, textured: 16 * GiB },
    systemRamBytes: 32 * GiB,
    requiredComponents: [
      "normal WSL2 Ubuntu 24.04 user distribution",
      "checksum-pinned Miniforge 26.5.3-0 under the normal user's home",
      "isolated Python 3.10 environment",
      "PyTorch 2.4.0 CUDA 12.1 runtime aligned with the official Kaolin/xFormers wheels",
      "NVIDIA Windows driver 531.14 or newer (CUDA 12.1 GA requirement)",
      "official TRELLIS source and submodules at pinned commit",
      "official TRELLIS text-xlarge and image-large weights at pinned revisions",
      "official CLIP text encoder at pinned revision (safetensors only)",
      "xFormers attention backend and native spconv mode; flash-attn is not required or installed",
      "pinned utils3d, nvdiffrast, mip-splatting and recovered upstream vox2seq source revisions",
      "octree rendering is outside the GLB generation path, so diffoctreerast is deliberately not installed",
    ],
  },
  {
    id: "meshy",
    name: "Meshy (cloud)",
    kind: "cloud",
    summary: "Optional external provider. Disabled until an API key is stored and each run's data/cost boundary is confirmed.",
    routes: ["direct-text", "image-to-3d"],
    enabledRoutes: [],
    geometry: "Provider-managed.", textures: "Provider-managed.", outputFormats: ["GLB"],
    qualitySpeed: "External service; capability, price and retention are account-plan dependent.", platform: "Cloud; uploads prompt/reference data.",
    sourceUrl: "https://docs.meshy.ai/", sourceRevision: "external-service", modelSources: [],
    sourceDependencies: [],
    licenseName: "Provider terms apply", licenseUrl: "https://www.meshy.ai/terms-of-use",
    downloadBytes: 0, installedBytes: 0, requiredFreeDiskBytes: 2 * GiB, physicalVramBytes: 0,
    minimumWindowsNvidiaDriver: "0",
    runVramBytes: { geometry: 0, textured: 0 }, systemRamBytes: 0, requiredComponents: ["User-supplied API key", "Per-run external-data and cost confirmation"],
  },
  {
    id: "tripo",
    name: "Tripo (cloud)",
    kind: "cloud",
    summary: "Optional external provider. Disabled until an API key is stored and each run's data/cost boundary is confirmed.",
    routes: ["direct-text", "image-to-3d"],
    enabledRoutes: [],
    geometry: "Provider-managed.", textures: "Provider-managed.", outputFormats: ["GLB"],
    qualitySpeed: "External service; capability, price and retention are account-plan dependent.", platform: "Cloud; uploads prompt/reference data.",
    sourceUrl: "https://platform.tripo3d.ai/docs", sourceRevision: "external-service", modelSources: [],
    sourceDependencies: [],
    licenseName: "Provider terms apply", licenseUrl: "https://www.tripo3d.ai/terms-of-service",
    downloadBytes: 0, installedBytes: 0, requiredFreeDiskBytes: 2 * GiB, physicalVramBytes: 0,
    minimumWindowsNvidiaDriver: "0",
    runVramBytes: { geometry: 0, textured: 0 }, systemRamBytes: 0, requiredComponents: ["User-supplied API key", "Per-run external-data and cost confirmation"],
  },
];

export const localProvider = (id: string) => {
  const found = PROMPT3D_PROVIDERS.find((p) => p.id === id && p.kind === "local");
  if (!found) throw new Error(`Unknown local Prompt-to-3D provider: ${id}`);
  return found;
};
